### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by chrisdraws** [Vadikus/practicalDL#2]
I realize this is not part of your tutorial, but I'm trying to start your tutorial.  

I'm on windows 10

I've installed Anaconda, which I've never used before.

I've cloned the repo and opened it in an Anaconda prompt. 

so I'm at 

```
$ D:\practicalDL
```
If I run 

```
$ D:\practicalDL>pip install -r requirements.txt
```

I get a whole bunch of errors 

```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Requirement already satisfied: jupyter in c:\users\userName\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (1.0.0)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/tensorflow/
Could not fetch URL https://pypi.org/simple/tensorflow/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/tensorflow/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement tensorflow (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for tensorflow (from -r requirements.txt (line 2))
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

Any advice?  I'm not a python person, but I'd really like to do this in python and follow along. I have a strong background in Javascript.  

Is the problem Windows10?  I guess I'could spin up a VM of unbuntu and try this there, but I was hoping not to have to work that way.

**Comment by Vadikus** [comment]
I haven't seen this problem before. But googling it leads to this: https://stackoverflow.com/questions/45954528/pip-is-configured-with-locations-that-require-tls-ssl-however-the-ssl-module-in
Please try and let me know if it works. Thanks!

**Comment by chrisdraws** [comment]
Thanks Vadim.

I had already added these three in my PATH.  So I tried that already.  This
is the location that Anaconda wanted to install itself.

C:\Users\username\anaconda3
C:\Users\username\anaconda3\Scripts
C:\Users\username\anaconda3\Library\bin

And I can't get Anaconda to run correctly in regular command prompt or in
the Anaconda command prompt.

I think I'm going to have to give up on running anaconda and try and run
your project directly and install Python locally.  Or try to install this
in a virtual Linux box.

**Comment by chrisdraws** [comment]
So i uninstalled and reinstalled to C:\Anaconda, just to see if that was the issue and I allowed anaconda to add the path variables so that they are in the path now.  Still not working.  In Anaconda prompt I tried running 

```
$ conda update conda
```

and I get this error 

```
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https://repo.anaconda.com/pkgs/main/win-64'

```

**Comment by chrisdraws** [comment]
this appears to be the solution.  Found at the bottom of this long thread. 

```
Removing both libssl-1_1-x64.dll and libcrypto-1_1-x64.dll in C:/Windows/System32/ fixed the problem for me.
```
https://github.com/pypa/virtualenv/issues/1139

**Comment by Vadikus** [comment]
Great! Thank you for letting me know. Hope it will help others if they run into this as well.
